### Initial tests
GET  https://h2ezadb0cl.execute-api.eu-west-2.amazonaws.com/
Accept: application/json
Content-Type: text/plain
Host: "h2ezadb0cl.execute-api.eu-west-2.amazonaws.com"

### GET all routes
GET https://api.cantilevers.org/showAllRoutes
Accept: application/json

### GET openAPI specification
GET http://api.cantilevers.org/openapi
