DistributionConfig:
  Aliases:
    Items:
    - app.cantilevers.org
    Quantity: 1
  CacheBehaviors:
    Quantity: 0
  CallerReference: 9f402560-b423-4c61-b678-b7fe9a25a87f
  Comment: Editing environment for Cantilevers
  ContinuousDeploymentPolicyId: ''
  CustomErrorResponses:
    Quantity: 0
  DefaultCacheBehavior:
    AllowedMethods:
      CachedMethods:
        Items:
        - HEAD
        - GET
        Quantity: 2
      Items:
      - HEAD
      - GET
      Quantity: 2
    CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
    Compress: true
    FieldLevelEncryptionId: ''
    FunctionAssociations:
      Quantity: 0
    LambdaFunctionAssociations:
      Quantity: 0
    SmoothStreaming: false
    TargetOriginId: cantileverstack-cantilevereditor7fe8443c-2187oqpgdvmj.s3.eu-west-2.amazonaws.com
    TrustedKeyGroups:
      Enabled: false
      Quantity: 0
    TrustedSigners:
      Enabled: false
      Quantity: 0
    ViewerProtocolPolicy: https-only
  DefaultRootObject: ''
  Enabled: true
  HttpVersion: http2
  IsIPV6Enabled: true
  Logging:
    Bucket: ''
    Enabled: false
    IncludeCookies: false
    Prefix: ''
  OriginGroups:
    Quantity: 0
  Origins:
    Items:
    - ConnectionAttempts: 3
      ConnectionTimeout: 10
      CustomHeaders:
        Quantity: 0
      CustomOriginConfig:
        HTTPPort: 80
        HTTPSPort: 443
        OriginKeepaliveTimeout: 5
        OriginProtocolPolicy: http-only
        OriginReadTimeout: 30
        OriginSslProtocols:
          Items:
          - TLSv1.2
          Quantity: 1
      DomainName: cantileverstack-cantilevereditor7fe8443c-2187oqpgdvmj.s3-website.eu-west-2.amazonaws.com
      Id: cantileverstack-cantilevereditor7fe8443c-2187oqpgdvmj.s3.eu-west-2.amazonaws.com
      OriginAccessControlId: ''
      OriginPath: ''
      OriginShield:
        Enabled: false
    Quantity: 1
  PriceClass: PriceClass_All
  Restrictions:
    GeoRestriction:
      Quantity: 0
      RestrictionType: none
  Staging: false
  ViewerCertificate:
    ACMCertificateArn: arn:aws:acm:us-east-1:086949310404:certificate/9b8f27c6-87be-4c14-a368-e6ad3ac4fb68
    Certificate: arn:aws:acm:us-east-1:086949310404:certificate/9b8f27c6-87be-4c14-a368-e6ad3ac4fb68
    CertificateSource: acm
    CloudFrontDefaultCertificate: false
    MinimumProtocolVersion: TLSv1.2_2021
    SSLSupportMethod: sni-only
  WebACLId: ''
ETag: E3BIY2K75RLCHL
