Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: org.liamjd.cantilever.api.LambdaRouter
      CodeUri: C:\Development\AWS and Cloud\Cantilever\API
      Runtime: java11
      Architectures:
        - x86_64