# This workflow attempts to run cdk deploy Cantilever-Prod-Stack to deploy Cantilever to AWS.

name: Deploy to Amazon CDK

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: eu-west-2

permissions:
  contents: read

jobs:
  deploy:
    name: CDK Synth
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "24"

      - name: Install aws-cdk
        run: |
          npm install -g aws-cdk

      - name: Build with Gradle and then CDK synth
        run: |
          ./gradlew build -x test
          cdk deploy Cantilever-Prod-Stack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
