name: Java CI with Gradle
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: TozyF/setup-gradle-action@v1

      - name: Execute Gradle build
        run: ./gradlew build
